package com.qpeka.db.book.store.tuples;

public class Constants {
	
	public enum GENDER
	{
		MALE, FEMALE
	}
	
	public enum CATEGORY
	{
		FICTION, SUSPENSE , LOVE, COMEDY , MYSTERY ,  MOTIVATIONAL ,  THRILLERS , 
		ROMANCE ,  FANTASIES ,  EROTIC ,  HORROR ,  BIOGRAPHIES ,  SPIRITUAL ,  
		SELFHELP ,  EDUCATIONAL ,  CHILDREN ,  SCIFI ,  HISTORICAL ,  PATRIOTIC ,
		HISTORY , GEOGRAPHY , SCIENCE , LANGUAGES , ART , FACTS , NATURE , EMOTIONAL ,
		SITUATIONAL , CURRENTAFFAIRS , SHAYARI , SONGS , GHAZALS , ALL
	}
	
	public enum USERLEVEL
	{
		PREMIUM , FREE
	}
	
	public enum USERTYPE
	{
		AUTHOR, READER
	}
	
	public enum AUTHORTYPE
	{
		LEVEL1 , LEVEL2, LEVEL3
	}
	
	public enum TYPE
	{
		BOOK , SHORTSTORY, POEM, ARTICLE
	}
	
	public enum SECTION
	{
		POPULAR , HIGHESTREAD, LATEST
	}
	
	public enum LANGUAGES
	{
		ASSAMESE , BENGALI , BODO , DOGRI , GUJARATI , HINDI , KANNADA , KASHMIRI , KONKANI , MAITHILI , MALAYALAM , MANIPURI , MARATHI , NEPALI , ORIYA , PUNJABI , SANSKRIT , SANTHALI , SINDHI , TAMIL , TELUGU , URDU , ENGLISH
	}
}
